const compounds = [
            // Cátions
            { formula: "Na<sup>+</sup>", name: "Cátion sódio", type: "cation", difficulty: "facil", tags: ["alcalino"] },
            { formula: "K<sup>+</sup>", name: "Cátion potássio", type: "cation", difficulty: "facil", tags: ["alcalino"] },
            { formula: "Li<sup>+</sup>", name: "Cátion lítio", type: "cation", difficulty: "facil", tags: ["alcalino"] },
            { formula: "Rb<sup>+</sup>", name: "Cátion rubídio", type: "cation", difficulty: "medio", tags: ["alcalino"] },
            { formula: "Cs<sup>+</sup>", name: "Cátion césio", type: "cation", difficulty: "medio", tags: ["alcalino"] },
            { formula: "Ca<sup>2+</sup>", name: "Cátion cálcio", type: "cation", difficulty: "facil", tags: ["alcalino_terroso"] },
            { formula: "Mg<sup>2+</sup>", name: "Cátion magnésio", type: "cation", difficulty: "facil", tags: ["alcalino_terroso"] },
            { formula: "Sr<sup>2+</sup>", name: "Cátion estrôncio", type: "cation", difficulty: "medio", tags: ["alcalino_terroso"] },
            { formula: "Ba<sup>2+</sup>", name: "Cátion bário", type: "cation", difficulty: "medio", tags: ["alcalino_terroso"] },
            { formula: "Be<sup>2+</sup>", name: "Cátion berílio", type: "cation", difficulty: "dificil", tags: ["alcalino_terroso"] },
            { formula: "Al<sup>3+</sup>", name: "Cátion alumínio", type: "cation", difficulty: "facil", tags: ["grupo13"] },
            { formula: "La<sup>3+</sup>", name: "Cátion lantânio", type: "cation", difficulty: "dificil", tags: ["raro"] },
            { formula: "Ce<sup>3+</sup>", name: "Cátion cério", type: "cation", difficulty: "dificil", tags: ["raro"] },
            { formula: "Fe<sup>2+</sup>", name: "Cátion ferro(II)", type: "cation", difficulty: "medio", tags: ["transicao", "carga_variavel", "ferro"] },
            { formula: "Fe<sup>3+</sup>", name: "Cátion ferro(III)", type: "cation", difficulty: "medio", tags: ["transicao", "carga_variavel", "ferro"] },
            { formula: "Cu<sup>+</sup>", name: "Cátion cobre(I)", type: "cation", difficulty: "medio", tags: ["transicao", "carga_variavel", "cobre"] },
            { formula: "Cu<sup>2+</sup>", name: "Cátion cobre(II)", type: "cation", difficulty: "medio", tags: ["transicao", "carga_variavel", "cobre"] },
            { formula: "NH<sub>4</sub><sup>+</sup>", name: "Cátion amônio", type: "cation", difficulty: "facil", tags: ["poliatomico"] },
            { formula: "N<sub>2</sub>H<sub>5</sub><sup>+</sup>", name: "Cátion hidrazínio", type: "cation", difficulty: "dificil", tags: ["poliatomico"] },
            { formula: "NO<sup>+</sup>", name: "Cátion nitrosila", type: "cation", difficulty: "dificil", tags: ["poliatomico"] },
            { formula: "NO<sub>2</sub><sup>+</sup>", name: "Cátion nitrila", type: "cation", difficulty: "dificil", tags: ["poliatomico"] },
            { formula: "Ag<sup>+</sup>", name: "Cátion prata", type: "cation", difficulty: "facil", tags: ["transicao"] },
            { formula: "Zn<sup>2+</sup>", name: "Cátion zinco", type: "cation", difficulty: "facil", tags: ["transicao"] },
            { formula: "Cd<sup>2+</sup>", name: "Cátion cádmio", type: "cation", difficulty: "medio", tags: ["transicao"] },
            { formula: "Hg<sub>2</sub><sup>2+</sup>", name: "Cátion mercúrio(I)", type: "cation", difficulty: "dificil", tags: ["transicao", "carga_variavel", "mercurio"] },
            { formula: "Hg<sup>2+</sup>", name: "Cátion mercúrio(II)", type: "cation", difficulty: "medio", tags: ["transicao", "carga_variavel", "mercurio"] },
            { formula: "Sn<sup>2+</sup>", name: "Cátion estanho(II)", type: "cation", difficulty: "medio", tags: ["post_transicao", "carga_variavel", "estanho"] },
            { formula: "Sn<sup>4+</sup>", name: "Cátion estanho(IV)", type: "cation", difficulty: "medio", tags: ["post_transicao", "carga_variavel", "estanho"] },
            { formula: "Pb<sup>2+</sup>", name: "Cátion chumbo(II)", type: "cation", difficulty: "medio", tags: ["post_transicao", "carga_variavel", "chumbo"] },
            { formula: "Pb<sup>4+</sup>", name: "Cátion chumbo(IV)", type: "cation", difficulty: "dificil", tags: ["post_transicao", "carga_variavel", "chumbo"] },
            { formula: "Au<sup>+</sup>", name: "Cátion ouro(I)", type: "cation", difficulty: "dificil", tags: ["transicao", "carga_variavel", "ouro"] },
            { formula: "Au<sup>3+</sup>", name: "Cátion ouro(III)", type: "cation", difficulty: "medio", tags: ["transicao", "carga_variavel", "ouro"] },
            { formula: "Cr<sup>2+</sup>", name: "Cátion cromo(II)", type: "cation", difficulty: "dificil", tags: ["transicao", "carga_variavel", "cromo"] },
            { formula: "Cr<sup>3+</sup>", name: "Cátion cromo(III)", type: "cation", difficulty: "medio", tags: ["transicao", "carga_variavel", "cromo"] },
            { formula: "Mn<sup>2+</sup>", name: "Cátion manganês(II)", type: "cation", difficulty: "medio", tags: ["transicao", "carga_variavel", "manganes"] },
            { formula: "Mn<sup>3+</sup>", name: "Cátion manganês(III)", type: "cation", difficulty: "dificil", tags: ["transicao", "carga_variavel", "manganes"] },
            { formula: "Co<sup>2+</sup>", name: "Cátion cobalto(II)", type: "cation", difficulty: "medio", tags: ["transicao", "carga_variavel", "cobalto"] },
            { formula: "Co<sup>3+</sup>", name: "Cátion cobalto(III)", type: "cation", difficulty: "dificil", tags: ["transicao", "carga_variavel", "cobalto"] },
            { formula: "Ni<sup>2+</sup>", name: "Cátion níquel(II)", type: "cation", difficulty: "medio", tags: ["transicao", "carga_variavel", "niquel"] },
            { formula: "Ni<sup>3+</sup>", name: "Cátion níquel(III)", type: "cation", difficulty: "dificil", tags: ["transicao", "carga_variavel", "niquel"] },
            { formula: "V<sup>2+</sup>", name: "Cátion vanádio(II)", type: "cation", difficulty: "dificil", tags: ["transicao", "carga_variavel", "vanadio"] },
            { formula: "V<sup>3+</sup>", name: "Cátion vanádio(III)", type: "cation", difficulty: "dificil", tags: ["transicao", "carga_variavel", "vanadio"] },
            { formula: "V<sup>4+</sup>", name: "Cátion vanádio(IV)", type: "cation", difficulty: "dificil", tags: ["transicao", "carga_variavel", "vanadio"] },
            { formula: "V<sup>5+</sup>", name: "Cátion vanádio(V)", type: "cation", difficulty: "dificil", tags: ["transicao", "carga_variavel", "vanadio"] },
            { formula: "Ti<sup>3+</sup>", name: "Cátion titânio(III)", type: "cation", difficulty: "dificil", tags: ["transicao", "carga_variavel", "titanio"] },
            { formula: "Ti<sup>4+</sup>", name: "Cátion titânio(IV)", type: "cation", difficulty: "medio", tags: ["transicao", "carga_variavel", "titanio"] },
            // Ânions
            { formula: "Cl<sup>-</sup>", name: "Ânion cloreto", type: "anion", difficulty: "facil", tags: ["haleto", "monoatomico"] },
            { formula: "F<sup>-</sup>", name: "Ânion fluoreto", type: "anion", difficulty: "facil", tags: ["haleto", "monoatomico"] },
            { formula: "Br<sup>-</sup>", name: "Ânion brometo", type: "anion", difficulty: "facil", tags: ["haleto", "monoatomico"] },
            { formula: "I<sup>-</sup>", name: "Ânion iodeto", type: "anion", difficulty: "facil", tags: ["haleto", "monoatomico"] },
            { formula: "S<sup>2-</sup>", name: "Ânion sulfeto", type: "anion", difficulty: "facil", tags: ["calcogenio", "monoatomico"] },
            { formula: "Se<sup>2-</sup>", name: "Ânion seleneto", type: "anion", difficulty: "medio", tags: ["calcogenio", "monoatomico"] },
            { formula: "Te<sup>2-</sup>", name: "Ânion telureto", type: "anion", difficulty: "dificil", tags: ["calcogenio", "monoatomico"] },
            { formula: "SO<sub>4</sub><sup>2-</sup>", name: "Ânion sulfato", type: "anion", difficulty: "facil", tags: ["oxianion", "enxofre"] },
            { formula: "SO<sub>3</sub><sup>2-</sup>", name: "Ânion sulfito", type: "anion", difficulty: "medio", tags: ["oxianion", "enxofre"] },
            { formula: "S<sub>2</sub>O<sub>3</sub><sup>2-</sup>", name: "Ânion tiossulfato", type: "anion", difficulty: "medio", tags: ["oxianion", "enxofre"] },
            { formula: "NO<sub>3</sub><sup>-</sup>", name: "Ânion nitrato", type: "anion", difficulty: "facil", tags: ["oxianion", "nitrogenio"] },
            { formula: "NO<sub>2</sub><sup>-</sup>", name: "Ânion nitrito", type: "anion", difficulty: "medio", tags: ["oxianion", "nitrogenio"] },
            { formula: "PO<sub>4</sub><sup>3-</sup>", name: "Ânion fosfato", type: "anion", difficulty: "medio", tags: ["oxianion", "fosforo"] },
            { formula: "PO<sub>3</sub><sup>3-</sup>", name: "Ânion fosfito", type: "anion", difficulty: "dificil", tags: ["oxianion", "fosforo"] },
            { formula: "H<sub>2</sub>PO<sub>4</sub><sup>-</sup>", name: "Ânion di-hidrogenofosfato", type: "anion", difficulty: "dificil", tags: ["hidrogenoanion", "fosforo"] },
            { formula: "HPO<sub>4</sub><sup>2-</sup>", name: "Ânion hidrogenofosfato", type: "anion", difficulty: "dificil", tags: ["hidrogenoanion", "fosforo"] },
            { formula: "Cr<sub>2</sub>O<sub>7</sub><sup>2-</sup>", name: "Ânion dicromato", type: "anion", difficulty: "dificil", tags: ["oxianion", "cromo"] },
            { formula: "CrO<sub>4</sub><sup>2-</sup>", name: "Ânion cromato", type: "anion", difficulty: "dificil", tags: ["oxianion", "cromo"] },
            { formula: "OCN<sup>-</sup>", name: "Ânion cianato", type: "anion", difficulty: "dificil", tags: ["poliatomico"] },
            { formula: "CNO<sup>-</sup>", name: "Ânion cianito", type: "anion", difficulty: "dificil", tags: ["poliatomico"] },
            { formula: "SCN<sup>-</sup>", name: "Ânion tiocianato", type: "anion", difficulty: "dificil", tags: ["poliatomico"] },
            { formula: "BrO<sub>4</sub><sup>-</sup>", name: "Ânion perbromato", type: "anion", difficulty: "dificil", tags: ["oxianion", "haleto"] },
            { formula: "BrO<sub>3</sub><sup>-</sup>", name: "Ânion bromato", type: "anion", difficulty: "medio", tags: ["oxianion", "haleto"] },
            { formula: "BrO<sub>2</sub><sup>-</sup>", name: "Ânion bromito", type: "anion", difficulty: "dificil", tags: ["oxianion", "haleto"] },
            { formula: "BrO<sup>-</sup>", name: "Ânion hipobromito", type: "anion", difficulty: "dificil", tags: ["oxianion", "haleto"] },
            { formula: "IO<sub>4</sub><sup>-</sup>", name: "Ânion periodato", type: "anion", difficulty: "dificil", tags: ["oxianion", "haleto"] },
            { formula: "IO<sub>3</sub><sup>-</sup>", name: "Ânion iodato", type: "anion", difficulty: "medio", tags: ["oxianion", "haleto"] },
            { formula: "IO<sub>2</sub><sup>-</sup>", name: "Ânion iodito", type: "anion", difficulty: "dificil", tags: ["oxianion", "haleto"] },
            { formula: "IO<sup>-</sup>", name: "Ânion hipoiodito", type: "anion", difficulty: "dificil", tags: ["oxianion", "haleto"] },
            { formula: "ClO<sub>4</sub><sup>-</sup>", name: "Ânion perclorato", type: "anion", difficulty: "dificil", tags: ["oxianion", "haleto"] },
            { formula: "ClO<sub>3</sub><sup>-</sup>", name: "Ânion clorato", type: "anion", difficulty: "medio", tags: ["oxianion", "haleto"] },
            { formula: "ClO<sub>2</sub><sup>-</sup>", name: "Ânion clorito", type: "anion", difficulty: "dificil", tags: ["oxianion", "haleto"] },
            { formula: "ClO<sup>-</sup>", name: "Ânion hipoclorito", type: "anion", difficulty: "medio", tags: ["oxianion", "haleto"] },
            { formula: "CO<sub>3</sub><sup>2-</sup>", name: "Ânion carbonato", type: "anion", difficulty: "facil", tags: ["oxianion", "carbono"] },
            { formula: "HCO<sub>3</sub><sup>-</sup>", name: "Ânion bicarbonato", type: "anion", difficulty: "medio", tags: ["hidrogenoanion", "carbono"] },
            { formula: "BO<sub>3</sub><sup>3-</sup>", name: "Ânion borato", type: "anion", difficulty: "dificil", tags: ["oxianion", "boro"] },
            { formula: "B<sub>4</sub>O<sub>7</sub><sup>2-</sup>", name: "Ânion tetraborato", type: "anion", difficulty: "dificil", tags: ["oxianion", "boro"] },
            { formula: "C<sub>2</sub>O<sub>4</sub><sup>2-</sup>", name: "Ânion oxalato", type: "anion", difficulty: "dificil", tags: ["oxianion", "carbono"] },
            { formula: "AsO<sub>4</sub><sup>3-</sup>", name: "Ânion arsenato", type: "anion", difficulty: "dificil", tags: ["oxianion", "arsenio"] },
            { formula: "AsO<sub>3</sub><sup>3-</sup>", name: "Ânion arsenito", type: "anion", difficulty: "dificil", tags: ["oxianion", "arsenio"] },
            { formula: "H<sub>2</sub>AsO<sub>4</sub><sup>-</sup>", name: "Ânion di-hidrogenoarsenato", type: "anion", difficulty: "dificil", tags: ["hidrogenoanion", "arsenio"] },
            { formula: "HAsO<sub>4</sub><sup>2-</sup>", name: "Ânion hidrogenoarsenato", type: "anion", difficulty: "dificil", tags: ["hidrogenoanion", "arsenio"] },
            { formula: "MnO<sub>4</sub><sup>-</sup>", name: "Ânion permanganato", type: "anion", difficulty: "medio", tags: ["oxianion", "manganes"] },
            { formula: "MnO<sub>4</sub><sup>2-</sup>", name: "Ânion manganato", type: "anion", difficulty: "dificil", tags: ["oxianion", "manganes"] },
            { formula: "VO<sub>4</sub><sup>3-</sup>", name: "Ânion vanadato", type: "anion", difficulty: "dificil", tags: ["oxianion", "vanadio"] },
            { formula: "VO<sub>3</sub><sup>-</sup>", name: "Ânion metavanadato", type: "anion", difficulty: "dificil", tags: ["oxianion", "vanadio"] },
            { formula: "WO<sub>4</sub><sup>2-</sup>", name: "Ânion wolframato", type: "anion", difficulty: "dificil", tags: ["oxianion", "tungstenio"] },
            { formula: "MoO<sub>4</sub><sup>2-</sup>", name: "Ânion molibdato", type: "anion", difficulty: "dificil", tags: ["oxianion", "molibdenio"] },
            { formula: "CH<sub>3</sub>COO<sup>-</sup>", name: "Ânion acetato", type: "anion", difficulty: "facil", tags: ["organico"] },
            { formula: "C<sub>2</sub>H<sub>3</sub>O<sub>2</sub><sup>-</sup>", name: "Ânion acetato (variante)", type: "anion", difficulty: "facil", tags: ["organico"] },
            { formula: "C<sub>6</sub>H<sub>5</sub>COO<sup>-</sup>", name: "Ânion benzoato", type: "anion", difficulty: "dificil", tags: ["organico"] },
            { formula: "C<sub>2</sub>O<sub>4</sub><sup>2-</sup>", name: "Ânion oxalato", type: "anion", difficulty: "medio", tags: ["organico"] },
            { formula: "N<sup>3-</sup>", name: "Ânion nitreto", type: "anion", difficulty: "medio", tags: ["monoatomico", "nitrogenio"] },
            { formula: "CS<sub>3</sub><sup>2-</sup>", name: "Ânion tiocarbonato", type: "anion", difficulty: "dificil", tags: ["poliatomico", "carbono", "enxofre"] },
            // Ácidos
            { formula: "HCl", name: "Ácido clorídrico", type: "acid", difficulty: "facil", tags: ["hidracido", "forte"] },
            { formula: "HF", name: "Ácido fluorídrico", type: "acid", difficulty: "medio", tags: ["hidracido", "moderado"] },
            { formula: "HBr", name: "Ácido bromídrico", type: "acid", difficulty: "facil", tags: ["hidracido", "forte"] },
            { formula: "HI", name: "Ácido iodídrico", type: "acid", difficulty: "facil", tags: ["hidracido", "forte"] },
            { formula: "H<sub>2</sub>S", name: "Ácido sulfídrico", type: "acid", difficulty: "medio", tags: ["hidracido", "fraco"] },
            { formula: "H<sub>2</sub>Se", name: "Ácido selenídrico", type: "acid", difficulty: "dificil", tags: ["hidracido", "fraco"] },
            { formula: "HCN", name: "Ácido cianídrico", type: "acid", difficulty: "medio", tags: ["hidracido", "fraco"] },
            { formula: "HSCN", name: "Ácido tiociânico", type: "acid", difficulty: "dificil", tags: ["hidracido", "forte"] },
            { formula: "HCNO", name: "Ácido cianítico", type: "acid", difficulty: "dificil", tags: ["hidracido", "fraco"] },
            { formula: "HOCN", name: "Ácido ciânico", type: "acid", difficulty: "dificil", tags: ["oxiacido", "fraco"] },
            { formula: "H<sub>2</sub>SO<sub>4</sub>", name: "Ácido sulfúrico", type: "acid", difficulty: "facil", tags: ["oxiacido", "forte"] },
            { formula: "H<sub>2</sub>SO<sub>3</sub>", name: "Ácido sulfuroso", type: "acid", difficulty: "medio", tags: ["oxiacido", "fraco"] },
            { formula: "H<sub>2</sub>S<sub>2</sub>O<sub>3</sub>", name: "Ácido tiossulfúrico", type: "acid", difficulty: "dificil", tags: ["oxiacido", "fraco"] },
            { formula: "HClO<sub>4</sub>", name: "Ácido perclórico", type: "acid", difficulty: "dificil", tags: ["oxiacido", "haleto", "forte"] },
            { formula: "HClO<sub>3</sub>", name: "Ácido clórico", type: "acid", difficulty: "medio", tags: ["oxiacido", "haleto", "forte"] },
            { formula: "HClO<sub>2</sub>", name: "Ácido cloroso", type: "acid", difficulty: "dificil", tags: ["oxiacido", "haleto", "fraco"] },
            { formula: "HClO", name: "Ácido hipocloroso", type: "acid", difficulty: "medio", tags: ["oxiacido", "haleto", "fraco"] },
            { formula: "HBrO<sub>4</sub>", name: "Ácido perbrômico", type: "acid", difficulty: "dificil", tags: ["oxiacido", "haleto", "forte"] },
            { formula: "HBrO<sub>3</sub>", name: "Ácido brômico", type: "acid", difficulty: "medio", tags: ["oxiacido", "haleto", "forte"] },
            { formula: "HBrO<sub>2</sub>", name: "Ácido bromoso", type: "acid", difficulty: "dificil", tags: ["oxiacido", "haleto", "fraco"] },
            { formula: "HBrO", name: "Ácido hipobromoso", type: "acid", difficulty: "dificil", tags: ["oxiacido", "haleto", "fraco"] },
            { formula: "HIO<sub>4</sub>", name: "Ácido periódico", type: "acid", difficulty: "dificil", tags: ["oxiacido", "haleto", "forte"] },
            { formula: "HIO<sub>3</sub>", name: "Ácido iódico", type: "acid", difficulty: "medio", tags: ["oxiacido", "haleto", "forte"] },
            { formula: "HIO<sub>2</sub>", name: "Ácido iodoso", type: "acid", difficulty: "dificil", tags: ["oxiacido", "haleto", "fraco"] },
            { formula: "HIO", name: "Ácido hipoiodoso", type: "acid", difficulty: "dificil", tags: ["oxiacido", "haleto", "fraco"] },
            { formula: "HNO<sub>3</sub>", name: "Ácido nítrico", type: "acid", difficulty: "facil", tags: ["oxiacido", "nitrogenio", "forte"] },
            { formula: "HNO<sub>2</sub>", name: "Ácido nitroso", type: "acid", difficulty: "medio", tags: ["oxiacido", "nitrogenio", "fraco"] },
            { formula: "H<sub>3</sub>PO<sub>4</sub>", name: "Ácido fosfórico", type: "acid", difficulty: "facil", tags: ["oxiacido", "fosforo", "moderado"] },
            { formula: "H<sub>3</sub>PO<sub>3</sub>", name: "Ácido fosforoso", type: "acid", difficulty: "medio", tags: ["oxiacido", "fosforo", "fraco"] },
            { formula: "H<sub>2</sub>CO<sub>3</sub>", name: "Ácido carbônico", type: "acid", difficulty: "facil", tags: ["oxiacido", "carbono", "fraco"] },
            { formula: "H<sub>3</sub>BO<sub>3</sub>", name: "Ácido bórico", type: "acid", difficulty: "medio", tags: ["oxiacido", "boro", "fraco"] },
            { formula: "H<sub>2</sub>C<sub>2</sub>O<sub>4</sub>", name: "Ácido oxálico", type: "acid", difficulty: "medio", tags: ["oxiacido", "carbono", "fraco"] },
            { formula: "HMnO<sub>4</sub>", name: "Ácido permangânico", type: "acid", difficulty: "medio", tags: ["oxiacido", "manganes", "forte"] },
            { formula: "H<sub>2</sub>CrO<sub>4</sub>", name: "Ácido crômico", type: "acid", difficulty: "medio", tags: ["oxiacido", "cromo", "forte"] },
            { formula: "H<sub>2</sub>Cr<sub>2</sub>O<sub>7</sub>", name: "Ácido dicrômico", type: "acid", difficulty: "medio", tags: ["oxiacido", "cromo", "forte"] },
            { formula: "H<sub>3</sub>AsO<sub>4</sub>", name: "Ácido arsênico", type: "acid", difficulty: "dificil", tags: ["oxiacido", "arsenio", "forte"] },
            { formula: "H<sub>3</sub>AsO<sub>3</sub>", name: "Ácido arsenoso", type: "acid", difficulty: "dificil", tags: ["oxiacido", "arsenio", "fraco"] },
            { formula: "H<sub>3</sub>VO<sub>4</sub>", name: "Ácido vanádico", type: "acid", difficulty: "dificil", tags: ["oxiacido", "vanadio", "fraco"] },
            { formula: "CH<sub>3</sub>COOH", name: "Ácido acético", type: "acid", difficulty: "facil", tags: ["organico", "fraco"] },
            { formula: "C<sub>6</sub>H<sub>5</sub>COOH", name: "Ácido benzoico", type: "acid", difficulty: "dificil", tags: ["organico", "fraco"] },
            // Bases
            { formula: "NaOH", name: "Hidróxido de sódio", type: "base", difficulty: "facil", tags: ["forte", "alcalino"] },
            { formula: "KOH", name: "Hidróxido de potássio", type: "base", difficulty: "facil", tags: ["forte", "alcalino"] },
            { formula: "LiOH", name: "Hidróxido de lítio", type: "base", difficulty: "medio", tags: ["forte", "alcalino"] },
            { formula: "RbOH", name: "Hidróxido de rubídio", type: "base", difficulty: "dificil", tags: ["forte", "alcalino"] },
            { formula: "CsOH", name: "Hidróxido de césio", type: "base", difficulty: "dificil", tags: ["forte", "alcalino"] },
            { formula: "Ca(OH)<sub>2</sub>", name: "Hidróxido de cálcio", type: "base", difficulty: "facil", tags: ["forte", "alcalino_terroso"] },
            { formula: "Mg(OH)<sub>2</sub>", name: "Hidróxido de magnésio", type: "base", difficulty: "medio", tags: ["fraca", "alcalino_terroso"] },
            { formula: "Sr(OH)<sub>2</sub>", name: "Hidróxido de estrôncio", type: "base", difficulty: "medio", tags: ["forte", "alcalino_terroso"] },
            { formula: "Ba(OH)<sub>2</sub>", name: "Hidróxido de bário", type: "base", difficulty: "medio", tags: ["forte", "alcalino_terroso"] },
            { formula: "Be(OH)<sub>2</sub>", name: "Hidróxido de berílio", type: "base", difficulty: "dificil", tags: ["anfotero", "alcalino_terroso"] },
            { formula: "Fe(OH)<sub>2</sub>", name: "Hidróxido de ferro(II)", type: "base", difficulty: "medio", tags: ["fraca", "transicao", "ferro"] },
            { formula: "Fe(OH)<sub>3</sub>", name: "Hidróxido de ferro(III)", type: "base", difficulty: "medio", tags: ["fraca", "transicao", "ferro"] },
            { formula: "Cu(OH)<sub>2</sub>", name: "Hidróxido de cobre(II)", type: "base", difficulty: "medio", tags: ["fraca", "transicao", "cobre"] },
            { formula: "Al(OH)<sub>3</sub>", name: "Hidróxido de alumínio", type: "base", difficulty: "medio", tags: ["fraca", "anfotero"] },
            { formula: "Zn(OH)<sub>2</sub>", name: "Hidróxido de zinco", type: "base", difficulty: "medio", tags: ["fraca", "anfotero"] },
            { formula: "Ni(OH)<sub>2</sub>", name: "Hidróxido de níquel(II)", type: "base", difficulty: "medio", tags: ["fraca", "transicao", "niquel"] },
            { formula: "Co(OH)<sub>2</sub>", name: "Hidróxido de cobalto(II)", type: "base", difficulty: "medio", tags: ["fraca", "transicao", "cobalto"] },
            { formula: "Cr(OH)<sub>3</sub>", name: "Hidróxido de cromo(III)", type: "base", difficulty: "dificil", tags: ["fraca", "anfotero"] },
            { formula: "Mn(OH)<sub>2</sub>", name: "Hidróxido de manganês(II)", type: "base", difficulty: "dificil", tags: ["fraca", "transicao", "manganes"] },
            { formula: "La(OH)<sub>3</sub>", name: "Hidróxido de lantânio", type: "base", difficulty: "dificil", tags: ["fraca", "raro"] },
            { formula: "Ce(OH)<sub>3</sub>", name: "Hidróxido de cério", type: "base", difficulty: "dificil", tags: ["fraca", "raro"] },
            { formula: "NH<sub>4</sub>OH", name: "Hidróxido de amônio", type: "base", difficulty: "facil", tags: ["fraca", "amonia"] },
            // Óxidos
            { formula: "CO<sub>2</sub>", name: "Dióxido de carbono", type: "oxide", difficulty: "facil", tags: ["acido", "ametal"] },
            { formula: "CO", name: "Monóxido de carbono", type: "oxide", difficulty: "facil", tags: ["neutro", "ametal"] },
            { formula: "Na<sub>2</sub>O", name: "Óxido de sódio", type: "oxide", difficulty: "facil", tags: ["basico", "metal"] },
            { formula: "K<sub>2</sub>O", name: "Óxido de potássio", type: "oxide", difficulty: "facil", tags: ["basico", "metal"] },
            { formula: "Li<sub>2</sub>O", name: "Óxido de lítio", type: "oxide", difficulty: "medio", tags: ["basico", "metal"] },
            { formula: "Rb<sub>2</sub>O", name: "Óxido de rubídio", type: "oxide", difficulty: "dificil", tags: ["basico", "metal"] },
            { formula: "Cs<sub>2</sub>O", name: "Óxido de césio", type: "oxide", difficulty: "dificil", tags: ["basico", "metal"] },
            { formula: "CaO", name: "Óxido de cálcio", type: "oxide", difficulty: "facil", tags: ["basico", "metal"] },
            { formula: "MgO", name: "Óxido de magnésio", type: "oxide", difficulty: "facil", tags: ["basico", "metal"] },
            { formula: "Al<sub>2</sub>O<sub>3</sub>", name: "Óxido de alumínio", type: "oxide", difficulty: "medio", tags: ["anfotero", "metal"] },
            { formula: "ZnO", name: "Óxido de zinco", type: "oxide", difficulty: "medio", tags: ["anfotero", "metal"] },
            { formula: "SO<sub>3</sub>", name: "Trióxido de enxofre", type: "oxide", difficulty: "medio", tags: ["acido", "ametal"] },
            { formula: "N<sub>2</sub>O", name: "Óxido nitroso", type: "oxide", difficulty: "medio", tags: ["neutro", "ametal"] },
            { formula: "NO", name: "Monóxido de nitrogênio", type: "oxide", difficulty: "medio", tags: ["neutro", "ametal"] },
            { formula: "N<sub>2</sub>O<sub>3</sub>", name: "Trióxido de dinitrogênio", type: "oxide", difficulty: "dificil", tags: ["acido", "ametal"] },
            { formula: "NO<sub>2</sub>", name: "Dióxido de nitrogênio", type: "oxide", difficulty: "dificil", tags: ["acido", "ametal"] },
            { formula: "N<sub>2</sub>O<sub>4</sub>", name: "Tetróxido de dinitrogênio", type: "oxide", difficulty: "dificil", tags: ["acido", "ametal"] },
            { formula: "N<sub>2</sub>O<sub>5</sub>", name: "Pentóxido de dinitrogênio", type: "oxide", difficulty: "dificil", tags: ["acido", "ametal"] },
            { formula: "P<sub>4</sub>O<sub>6</sub>", name: "Hexaóxido de tetrafósforo", type: "oxide", difficulty: "dificil", tags: ["acido", "ametal"] },
            { formula: "P<sub>4</sub>O<sub>10</sub>", name: "Decaóxido de tetrafósforo", type: "oxide", difficulty: "medio", tags: ["acido", "ametal"] },
            { formula: "Cl<sub>2</sub>O", name: "Monóxido de dicloro", type: "oxide", difficulty: "dificil", tags: ["acido", "ametal"] },
            { formula: "Cl<sub>2</sub>O<sub>3</sub>", name: "Trióxido de dicloro", type: "oxide", difficulty: "dificil", tags: ["acido", "ametal"] },
            { formula: "Cl<sub>2</sub>O<sub>5</sub>", name: "Pentóxido de dicloro", type: "oxide", difficulty: "dificil", tags: ["acido", "ametal"] },
            { formula: "Cl<sub>2</sub>O<sub>7</sub>", name: "Heptóxido de dicloro", type: "oxide", difficulty: "dificil", tags: ["acido", "ametal"] },
            { formula: "H<sub>2</sub>O<sub>2</sub>", name: "Peróxido de hidrogênio", type: "oxide", difficulty: "dificil", tags: ["peroxido"] },
            { formula: "Na<sub>2</sub>O<sub>2</sub>", name: "Peróxido de sódio", type: "oxide", difficulty: "dificil", tags: ["peroxido"] },
            { formula: "BaO<sub>2</sub>", name: "Peróxido de bário", type: "oxide", difficulty: "dificil", tags: ["peroxido"] },
            { formula: "CaO<sub>2</sub>", name: "Peróxido de cálcio", type: "oxide", difficulty: "dificil", tags: ["peroxido"] },
            { formula: "BeO", name: "Óxido de berílio", type: "oxide", difficulty: "dificil", tags: ["anfotero", "metal"] },
            { formula: "PbO", name: "Óxido de chumbo(II)", type: "oxide", difficulty: "medio", tags: ["anfotero", "metal"] },
            { formula: "SnO", name: "Óxido de estanho(II)", type: "oxide", difficulty: "medio", tags: ["anfotero", "metal"] },
            { formula: "SnO<sub>2</sub>", name: "Óxido de estanho(IV)", type: "oxide", difficulty: "medio", tags: ["anfotero", "metal"] },
            { formula: "Cr<sub>2</sub>O<sub>3</sub>", name: "Óxido de cromo(III)", type: "oxide", difficulty: "medio", tags: ["anfotero", "metal"] },
            { formula: "MnO<sub>2</sub>", name: "Óxido de manganês(IV)", type: "oxide", difficulty: "medio", tags: ["anfotero", "metal"] },
            { formula: "Fe<sub>3</sub>O<sub>4</sub>", name: "Óxido misto de ferro(II,III)", type: "oxide", difficulty: "dificil", tags: ["misto", "metal"] },
            { formula: "Pb<sub>3</sub>O<sub>4</sub>", name: "Óxido misto de chumbo(II,IV)", type: "oxide", difficulty: "dificil", tags: ["misto", "metal"] },
            { formula: "V<sub>2</sub>O<sub>5</sub>", name: "Pentóxido de divanádio", type: "oxide", difficulty: "medio", tags: ["anfotero", "metal", "vanadio"] },
            { formula: "VO<sub>2</sub>", name: "Dióxido de vanádio", type: "oxide", difficulty: "dificil", tags: ["anfotero", "metal", "vanadio"] },
            { formula: "V<sub>2</sub>O<sub>3</sub>", name: "Trióxido de divanádio", type: "oxide", difficulty: "dificil", tags: ["basico", "metal", "vanadio"] },
            { formula: "VO", name: "Monóxido de vanádio", type: "oxide", difficulty: "dificil", tags: ["basico", "metal", "vanadio"] },
            // Sais
            { formula: "NaCl", name: "Cloreto de sódio", type: "salt", difficulty: "facil", tags: ["haleto", "alcalino"] },
            { formula: "KCl", name: "Cloreto de potássio", type: "salt", difficulty: "facil", tags: ["haleto", "alcalino"] },
            { formula: "LiCl", name: "Cloreto de lítio", type: "salt", difficulty: "medio", tags: ["haleto", "alcalino"] },
            { formula: "NH<sub>4</sub>Cl", name: "Cloreto de amônio", type: "salt", difficulty: "facil", tags: ["haleto", "amonio"] },
            { formula: "CaCO<sub>3</sub>", name: "Carbonato de cálcio", type: "salt", difficulty: "facil", tags: ["carbonato", "alcalino_terroso"] },
            { formula: "Na<sub>2</sub>CO<sub>3</sub>", name: "Carbonato de sódio", type: "salt", difficulty: "facil", tags: ["carbonato", "alcalino"] },
            { formula: "K<sub>2</sub>CO<sub>3</sub>", name: "Carbonato de potássio", type: "salt", difficulty: "medio", tags: ["carbonato", "alcalino"] },
            { formula: "MgCO<sub>3</sub>", name: "Carbonato de magnésio", type: "salt", difficulty: "medio", tags: ["carbonato", "alcalino_terroso"] },
            { formula: "FeSO<sub>4</sub>", name: "Sulfato de ferro(II)", type: "salt", difficulty: "medio", tags: ["sulfato", "transicao", "ferro"] },
            { formula: "Fe<sub>2</sub>(SO<sub>4</sub>)<sub>3</sub>", name: "Sulfato de ferro(III)", type: "salt", difficulty: "medio", tags: ["sulfato", "transicao", "ferro"] },
            { formula: "AgNO<sub>3</sub>", name: "Nitrato de prata", type: "salt", difficulty: "medio", tags: ["nitrato", "transicao"] },
            { formula: "Cu<sub>2</sub>S", name: "Sulfeto de cobre(I)", type: "salt", difficulty: "dificil", tags: ["sulfeto", "transicao", "cobre"] },
            { formula: "NaHCO<sub>3</sub>", name: "Bicarbonato de sódio", type: "salt", difficulty: "medio", tags: ["hidrogenossal", "carbonato"] },
            { formula: "NaH<sub>2</sub>PO<sub>4</sub>", name: "Di-hidrogenofosfato de sódio", type: "salt", difficulty: "dificil", tags: ["hidrogenossal", "fosfato"] },
            { formula: "Na<sub>2</sub>HPO<sub>4</sub>", name: "Hidrogenofosfato de sódio", type: "salt", difficulty: "dificil", tags: ["hidrogenossal", "fosfato"] },
            { formula: "K<sub>2</sub>Cr<sub>2</sub>O<sub>7</sub>", name: "Dicromato de potássio", type: "salt", difficulty: "dificil", tags: ["dicromato", "alcalino"] },
            { formula: "PbCrO<sub>4</sub>", name: "Cromato de chumbo(II)", type: "salt", difficulty: "dificil", tags: ["cromato", "transicao"] },
            { formula: "KOCN", name: "Cianato de potássio", type: "salt", difficulty: "dificil", tags: ["cianato", "alcalino"] },
            { formula: "NH<sub>4</sub>SCN", name: "Tiocianato de amônio", type: "salt", difficulty: "dificil", tags: ["tiocianato", "amonio"] },
            { formula: "KClO", name: "Hipoclorito de potássio", type: "salt", difficulty: "medio", tags: ["oxianion", "haleto"] },
            { formula: "Ca(BrO<sub>3</sub>)<sub>2</sub>", name: "Bromato de cálcio", type: "salt", difficulty: "dificil", tags: ["oxianion", "haleto"] },
            { formula: "AgBr", name: "Brometo de prata", type: "salt", difficulty: "medio", tags: ["haleto", "transicao"] },
            { formula: "AgI", name: "Iodeto de prata", type: "salt", difficulty: "medio", tags: ["haleto", "transicao"] },
            { formula: "SnCl<sub>2</sub>", name: "Cloreto de estanho(II)", type: "salt", difficulty: "medio", tags: ["haleto", "post_transicao", "estanho"] },
            { formula: "SnCl<sub>4</sub>", name: "Cloreto de estanho(IV)", type: "salt", difficulty: "medio", tags: ["haleto", "post_transicao", "estanho"] },
            { formula: "PbCl<sub>4</sub>", name: "Cloreto de chumbo(IV)", type: "salt", difficulty: "dificil", tags: ["haleto", "post_transicao", "chumbo"] },
            { formula: "Na<sub>2</sub>S", name: "Sulfeto de sódio", type: "salt", difficulty: "medio", tags: ["sulfeto", "alcalino"] },
            { formula: "Na<sub>2</sub>S<sub>2</sub>O<sub>3</sub>", name: "Tiossulfato de sódio", type: "salt", difficulty: "medio", tags: ["tiossulfato", "alcalino"] },
            { formula: "CaSO<sub>4</sub>", name: "Sulfato de cálcio", type: "salt", difficulty: "facil", tags: ["sulfato", "alcalino_terroso"] },
            { formula: "BaSO<sub>4</sub>", name: "Sulfato de bário", type: "salt", difficulty: "facil", tags: ["sulfato", "alcalino_terroso"] },
            { formula: "CuSO<sub>4</sub>", name: "Sulfato de cobre(II)", type: "salt", difficulty: "facil", tags: ["sulfato", "transicao", "cobre"] },
            { formula: "MgSO<sub>4</sub>", name: "Sulfato de magnésio", type: "salt", difficulty: "facil", tags: ["sulfato", "alcalino_terroso"] },
            { formula: "Na<sub>2</sub>SO<sub>3</sub>", name: "Sulfito de sódio", type: "salt", difficulty: "medio", tags: ["sulfito", "alcalino"] },
            { formula: "CdS", name: "Sulfeto de cádmio", type: "salt", difficulty: "dificil", tags: ["sulfeto", "transicao"] },
            { formula: "ZnS", name: "Sulfeto de zinco", type: "salt", difficulty: "medio", tags: ["sulfeto", "transicao"] },
            { formula: "FeS", name: "Sulfeto de ferro(II)", type: "salt", difficulty: "medio", tags: ["sulfeto", "transicao", "ferro"] },
            { formula: "KNO<sub>3</sub>", name: "Nitrato de potássio", type: "salt", difficulty: "facil", tags: ["nitrato", "alcalino"] },
            { formula: "NH<sub>4</sub>NO<sub>3</sub>", name: "Nitrato de amônio", type: "salt", difficulty: "facil", tags: ["nitrato", "amonio"] },
            { formula: "NaNO<sub>2</sub>", name: "Nitrito de sódio", type: "salt", difficulty: "medio", tags: ["nitrito", "alcalino"] },
            { formula: "Ca<sub>3</sub>(PO<sub>4</sub>)<sub>2</sub>", name: "Fosfato de cálcio", type: "salt", difficulty: "medio", tags: ["fosfato", "alcalino_terroso"] },
            { formula: "Na<sub>3</sub>PO<sub>4</sub>", name: "Fosfato de sódio", type: "salt", difficulty: "medio", tags: ["fosfato", "alcalino"] },
            { formula: "Ca(H<sub>2</sub>PO<sub>4</sub>)<sub>2</sub>", name: "Fosfato monoácido de cálcio", type: "salt", difficulty: "dificil", tags: ["fosfato", "alcalino_terroso"] },
            { formula: "Ag<sub>3</sub>PO<sub>4</sub>", name: "Fosfato de prata", type: "salt", difficulty: "dificil", tags: ["fosfato", "transicao"] },
            { formula: "Na<sub>2</sub>B<sub>4</sub>O<sub>7</sub>", name: "Tetraborato de sódio (Borax)", type: "salt", difficulty: "dificil", tags: ["borato", "alcalino"] },
            { formula: "Ca<sub>10</sub>(PO<sub>4</sub>)<sub>6</sub>(OH)<sub>2</sub>", name: "Hidroxiapatita", type: "salt", difficulty: "dificil", tags: ["fosfato", "alcalino_terroso"] },
            { formula: "CaSO<sub>4</sub>·2H<sub>2</sub>O", name: "Gesso", type: "salt", difficulty: "medio", tags: ["sulfato", "alcalino_terroso"] },
            { formula: "Fe<sub>3</sub>O<sub>4</sub>", name: "Magnetita", type: "salt", difficulty: "dificil", tags: ["misto", "ferro"] },
            { formula: "Pb<sub>3</sub>O<sub>4</sub>", name: "Minio", type: "salt", difficulty: "dificil", tags: ["misto", "chumbo"] },
            { formula: "FeTiO<sub>3</sub>", name: "Ilmenita", type: "salt", difficulty: "dificil", tags: ["titanato", "ferro"] },
            // Carbonatos extras
            { formula: "BaCO<sub>3</sub>", name: "Carbonato de bário", type: "salt", difficulty: "medio", tags: ["carbonato", "alcalino_terroso"] },
            { formula: "Li<sub>2</sub>CO<sub>3</sub>", name: "Carbonato de lítio", type: "salt", difficulty: "medio", tags: ["carbonato", "alcalino"] },
            { formula: "Ag<sub>2</sub>CO<sub>3</sub>", name: "Carbonato de prata", type: "salt", difficulty: "dificil", tags: ["carbonato", "transicao"] },
            { formula: "ZnCO<sub>3</sub>", name: "Carbonato de zinco", type: "salt", difficulty: "medio", tags: ["carbonato", "transicao"] },
            { formula: "CuCO<sub>3</sub>", name: "Carbonato de cobre(II)", type: "salt", difficulty: "dificil", tags: ["carbonato", "transicao", "cobre"] },
            // Pares confusos de Enxofre
            { formula: "Na<sub>2</sub>SO<sub>4</sub>", name: "Sulfato de sódio", type: "salt", difficulty: "facil", tags: ["sulfato", "alcalino", "enxofre"] },
            { formula: "K<sub>2</sub>SO<sub>4</sub>", name: "Sulfato de potássio", type: "salt", difficulty: "facil", tags: ["sulfato", "alcalino", "enxofre"] },
            { formula: "K<sub>2</sub>SO<sub>3</sub>", name: "Sulfito de potássio", type: "salt", difficulty: "medio", tags: ["sulfito", "alcalino", "enxofre"] },
            { formula: "K<sub>2</sub>S", name: "Sulfeto de potássio", type: "salt", difficulty: "medio", tags: ["sulfeto", "alcalino", "enxofre"] },
            { formula: "K<sub>2</sub>S<sub>2</sub>O<sub>3</sub>", name: "Tiossulfato de potássio", type: "salt", difficulty: "dificil", tags: ["tiossulfato", "alcalino", "enxofre"] },
            { formula: "Ag<sub>2</sub>S", name: "Sulfeto de prata", type: "salt", difficulty: "medio", tags: ["sulfeto", "transicao", "enxofre"] },
            // Sais de Vanádio
            { formula: "NaVO<sub>3</sub>", name: "Metavanadato de sódio", type: "salt", difficulty: "dificil", tags: ["vanadato", "alcalino", "vanadio"] },
            { formula: "Na<sub>3</sub>VO<sub>4</sub>", name: "Ortovanadato de sódio", type: "salt", difficulty: "dificil", tags: ["vanadato", "alcalino", "vanadio"] },
            { formula: "V<sub>2</sub>(SO<sub>4</sub>)<sub>3</sub>", name: "Sulfato de vanádio(III)", type: "salt", difficulty: "dificil", tags: ["sulfato", "transicao", "vanadio"] },
            { formula: "VOSO<sub>4</sub>", name: "Sulfato de vanadila", type: "salt", difficulty: "dificil", tags: ["sulfato", "misto", "vanadio"] }
        ];